curl 'http://cofcredit.cofina.localhost/api/auth/login' \
  -H 'sec-ch-ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'authorization: Bearer 25|2P0IrDm41pQXu38AQhDQ1tC6eGDl5LoRD5ZWiGml3bc853fb' \
  -H 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'accept: application/json' \
  -H 'Referer: http://cofcredit.cofina.localhost/login' \
  -H 'sec-ch-ua-platform: "Android"' \
  --data-raw '{"email":"charles.gamligo@cofinacorp.com","password":"Coftg2021"}' \
  --compressed
