SELECT
	DISTINCT C.MATRICULE_CLIENT,
	C.INTITULE_COMPTE,
	C.NO_COMPTE              "NO_COMPTE",
	C.CODE_BUREAU            "CODE_AGENCE",
	B.LIBELLE_BUREAU         "AGENCE",
	CA.INT_CATEGORIE,
	AF.NOM_APPAFF,
	CL.SEXE,
	G.NOM_GESTIONNAIRE,
	CL.CODE_SSECTEUR,
	SS.LIB_SSECT,
	CL.LIEU_NAISSANCE,
	CL.TEL_PORT,
	CL.DATE_NAISSANCE,
	CL.CODE_NATION,
	P.LIB_NATION,
	CL.ADRESSE_1,
	CL.CODE_TYPE_PIECE,
	TP.LIBELLE_TYPE          "TYPE_PIECE",
	CL.NUMERO_PIECE_IDENTITE
FROM
	COFINATG.COMPTE       C,
	COFINATG.TYPE_COMPTE  T,
	COFINATG.GESTIONNAIRE G,
	COFINATG.APP_AFFAIRE  AF,
	COFINATG.CLIENT       CL,
	COFINATG.CATEGORIE    CA,
	COFINATG.BUREAU       B,
	COFINATG.SOUS_SECTEUR SS,
	COFINATG.PAYS         P,
	COFINATG.TYPE_PIECE   TP
WHERE
	C.CODE_TYPE_CPT=T.CODE_TYPE_CPT
	AND SS.CODE_SSECT(+)=CL.CODE_SSECTEUR
	AND C.MATRICULE_CLIENT=CL.MATRICULE_CLIENT
	AND CL.CODE_CATEGORIE= CA.CODE_CATEGORIE
	AND G.CODE_GESTIONNAIRE(+)=CL.CODE_GESTIONNAIRE
	AND AF.CODE_APPAFF(+)=CL.CODE_APPAFF
	AND C.CODE_BUREAU=B.CODE_BUREAU
	AND T.PROD_CONCERNE IN ('1', '3')
	AND CL.MATRICULE_CLIENT NOT LIKE '999%'
	AND C.NO_COMPTE LIKE '251%'
	AND C.CODE_BUREAU=B.CODE_BUREAU
	AND C.STATUS_COMPTE='O'
	AND T.CPT_INTERNE='N'
	AND C.CODE_TYPE_CPT='25101'
	AND CL.CODE_NATION = P.CODE_PAYS
	AND CL.CODE_TYPE_PIECE = TP.CODE_TYPE;